site_name: My Docs
theme: 
  name: material
  palette:
    scheme: preference
    primary: blue grey
    accent: teal
  features:
    - tabs
plugins:
  - search
  - awesome-pages:
      filename: index.yml
      collapse_single_pages: false
  - git-revision-date-localized:
      type: timeago
  - macros
  - rss
markdown_extensions:
  - codehilite:
      linenums: true
      guess_lang: false
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - toc:
      permalink: true
extra:
  foo: bar
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dersimn
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/dersimn
    - icon: fontawesome/brands/bitbucket
      link: https://bitbucket.org/dersimn
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
repo_name: dersimn.github.io
repo_url: https://github.com/dersimn/dersimn.github.io