---
site_name: My Docs
theme:
  name: material
  palette:
    scheme: preference
    primary: blue grey
    accent: teal
  features:
    - navigation.tabs
plugins:
  - search
  - awesome-pages:
      filename: index.yml
      collapse_single_pages: false
  - git-revision-date-localized:
      type: timeago
  - macros
  - rss
markdown_extensions:
  - pymdownx.highlight:
      linenums: true
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - toc:
      permalink: true
  - pymdownx.tasklist:
      custom_checkbox: true
  - pymdownx.keys
extra:
  foo: bar
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/dersimn
    - icon: fontawesome/brands/docker
      link: https://hub.docker.com/r/dersimn
    - icon: fontawesome/brands/bitbucket
      link: https://bitbucket.org/dersimn
    - icon: fontawesome/solid/cube
      link: https://thingiverse.com/dersimn
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML
repo_name: dersimn.github.io
repo_url: https://github.com/dersimn/dersimn.github.io
copyright: <a href="https://creativecommons.org/licenses/by-sa/3.0/de/deed.en">CC BY-SA 3.0 DE</a> – Simon Christmann
