site_name: My Docs
theme: 
  name: material
  palette:
    scheme: preference
plugins:
  - search
  - awesome-pages:
      filename: index.yml
      collapse_single_pages: false
  - git-revision-date-localized:
      type: timeago
  - macros
markdown_extensions:
  - codehilite:
      linenums: true
      guess_lang: false
  - pymdownx.tabbed
  - pymdownx.superfences
  - pymdownx.arithmatex
  - admonition
  - footnotes
  - toc:
      permalink: true
extra:
  foo: bar
extra_javascript:
  - https://cdnjs.cloudflare.com/ajax/libs/mathjax/2.7.0/MathJax.js?config=TeX-MML-AM_CHTML