site_name: My Docs
theme: material
plugins:
  - search
  - awesome-pages:
      filename: index.yml
      collapse_single_pages: false
  - git-revision-date-localized:
      type: timeago
  - macros
extra:
  foo: bar
